# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
  - main
pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.14'
            displayName: 'Install Node.js'
          - script: |
              cd Parisjanitor
              npm run build
            displayName: 'npm install, buid, and test'
          - script: |
              cd PrisJanitor
            displayName: 'npm install, buid, and test'
          - task: ArchiveFiles@2
            displayName: Archive build artifact
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/paris-janitor-front.zip'
              replaceExistingArchive: false
          - task: PublishBuildArtifacts@1
            displayName: Publish build artifact
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/paris-janitor-front.zip'
              ArtifactName: 'petpals-backoffice'